BetterEmbed:
  NeosEmbed:
    text:
      msgClick: 'With a click on the link below, the original content will be loaded. This can include remote content and you can possibly be tracked from the original provider.'
      mdgGdpr: 'Text should be adopted for your GDPR needs'
      labelOk: 'show original content'
      labelCancel: 'close'
